version: '3.9'

services:
  redis:
    image: redis:7
    container_name: payments_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  transfer-pg-db:
    image: postgres:15
    container_name: transfer-db
    environment:
      POSTGRES_DB: transfer_db
      POSTGRES_USER: transfer_user
      POSTGRES_PASSWORD: password321
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transfer_user"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - transfer-pgdata:/var/lib/postgresql/data

  ledger-pg-db:
    image: postgres:15
    container_name: ledger-db
    environment:
      POSTGRES_DB: ledger_db
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: password456
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger_user"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ledger-pgdata:/var/lib/postgresql/data

  ledger-service:
    build:
      context: ./ledger-service
      dockerfile: Dockerfile
    container_name: ledger-service
    restart: always
    environment:
      LEDGER_DB_URL: jdbc:postgresql://ledger-pg-db:5432/ledger_db
      LEDGER_DB_USER: ledger_user
      LEDGER_DB_PWD: password456
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8081
      SWAGGER_ENABLED: "true"
    depends_on:
      ledger-pg-db:
        condition: service_healthy
    ports:
      - "8081:8081"

  transfer-service:
    build:
      context: ./transfer-service
      dockerfile: Dockerfile
    container_name: transfer-service
    restart: always
    environment:
      TRANSFER_DB_URL: jdbc:postgresql://transfer-pg-db:5432/transfer_db
      TRANSFER_DB_USER: transfer_user
      TRANSFER_DB_PWD: password321
      REDIS_HOST: redis
      SPRING_PROFILES_ACTIVE: dev
      SWAGGER_ENABLED: "true"
      LEDGER_BASE_URL: http://ledger-service:8081
    depends_on:
      redis:
        condition: service_healthy
      transfer-pg-db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  ledger-pgdata:
  transfer-pgdata: