spring:
  application:
    name: transfer-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:transfer_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: pwd123
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

  data:
    redis:
      host: localhost
      port: 6379
management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

ledger:
  service:
    base-url: http://localhost:8081

transfer:
  batch:
    max-transfer-size: 20
    thread-pool-size: 10
    queue-capacity: 100
  idempotency:
    ttl: 200s # ISO format
  outbox:
    max-retries: 5
    base-backoff-seconds: 25

resilience4j.circuitbreaker:
    instances:
      ledgerApiCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 4
        registerHealthIndicator: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{X-Request-ID}] %logger{36} - %msg%n"