spring:
  application:
    name: ledger-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ledger_db
    username: ledger_user
    password: password456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
  jackson:
    default-property-inclusion: NON_EMPTY

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{X-Request-ID}] %logger{36} - %msg%n"