spring:
  application:
    name: ledger-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${LEDGER_DB_URL:jdbc:postgresql://localhost:5432/ledger_db}
    username: ${LEDGER_DB_USER:ledger_user}
    password: ${LEDGER_DB_PWD}
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
  jackson:
    default-property-inclusion: NON_EMPTY

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  open-api:
    info:
      title: Ledger API
      description: Accounts and Ledger API documentation
      version: 1.0.0

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{X-Request-ID}] %logger{36} - %msg%n"