name: Ledger Service CI

on:
  push:
    paths:
      - 'ledger-service/**'
  pull_request:
    paths:
      - 'ledger-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Run SpotBugs
        run: mvn -B clean install -DskipTests --file ledger-service/pom.xml

      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-report
          path: target/spotbugs.html

      - name: Run Unit Tests
        run: mvn -B test --file ledger-service/pom.xml

      - name: Run Unit Tests
        run: mvn -B test --file ledger-service/pom.xml

      - name: Run Integration Tests
        run: mvn -B verify --file ledger-service/pom.xml
